version: '3.9'

services:
    nginx:
        image: nginx:alpine
        ports:
            - "8000:8000"
        volumes:
            - ./docker/development/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - jenkins

    jenkins:
        build:
            context: ./docker/common/jenkins
        environment:
            DOCKER_HOST: tcp://jenkins-docker:2376      # host variable for work with jenkins-docker service
            DOCKER_CERT_PATH: /certs/client             # where store certs for work with jenkins-docker service
            DOCKER_TLS_VERIFY: 1                        # enable encryption for use jenkins-docker service certs
        volumes:
            - jenkins-data:/var/jenkins_home    # access to jenkins files
            - docker-certs:/certs/client:ro     # get docker client certs with mode read only
        depends_on:
            - jenkins-docker

    jenkins-docker:
        image: docker:dind
        privileged: true
        environment:
            DOCKER_TLS_CERTDIR: /certs          # where store certs for work with this docker service from outside
        volumes:
            - jenkins-data:/var/jenkins_home    # access to jenkins files
            - docker-certs:/certs/client        # client certs for jenkins service
            - docker-data:/var/lib/docker       # volume for downloaded docker images

volumes:
    jenkins-data:
    docker-certs:
    docker-data:
